const {Discord, Collection, Client, MessageEmbed, MessageActionRow, MessageSelectMenu, MessageButton, Message} = require('discord.js');
const client = new Client({
     intents: [
         "GUILDS",
         "GUILD_MEMBERS",
         "GUILD_BANS",
         "GUILD_INTEGRATIONS",
         "GUILD_WEBHOOKS",
         "GUILD_INVITES",
         "GUILD_VOICE_STATES",
         "GUILD_PRESENCES",
         "GUILD_MESSAGES",
         "GUILD_MESSAGE_REACTIONS",
         "GUILD_MESSAGE_TYPING",
         "DIRECT_MESSAGES",
         "DIRECT_MESSAGE_REACTIONS",
         "DIRECT_MESSAGE_TYPING",
     ],
 });
 
 //EXPORTS CLIENT
 module.exports = client;
 
const config = require('./config.json');
let CurrentChannel = false;
let changedMember = [];
let prefixvip = null
let car = null
let ped = null 
let money = null
client.on('ready', () => {
     console.log('^5 [Fly] ^2BOT Ready^0')
})

client.on('messageCreate', async (message, interaction) => {
    CurrentChannel = message.channel;
    const args = message.content.substring().split(" ");
     if (message.author.bot) return;
    if (message.content.startsWith(config.prefix)) {
        if (args[0] == config.prefix + 'generate') {
          if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.reply(`${message.author} **You do not have permissions to use this command.**`); 
            let r2 = Math.floor((Math.random() * 98) + 1);
            let r8 = Math.floor((Math.random() * 98) + 1);
            let r9 = Math.floor((Math.random() * 98) + 1);

            const letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            const letras2 = "abcdefghijklmnopqrstuvwxyz"
            
            let r1 =  letras[Math.floor(Math.random() * letras.length)]
            let r7 =  letras[Math.floor(Math.random() * letras.length)]
            let r6 =  letras[Math.floor(Math.random() * letras.length)]
            let r5 =  letras[Math.floor(Math.random() * letras.length)]
            
            let r3 = letras2[Math.floor(Math.random() * letras2.length)]
            
            let r4 = Math.floor((Math.random() * 80) + 1);
            let codigo = 'd-'+r1+r2+r3+r6+r8+r4+r5+r9+r7

            const embed = new MessageEmbed()
            .setTitle('Generate a VIP')
            .setColor('GOLD')
    
            const row = new MessageActionRow()
            .addComponents(
              new MessageSelectMenu()
              .setCustomId('typevip')
              .setPlaceholder('Select it here')
              .addOptions([{
                  label: "VIP Bronze",
                  value: "Bronze",
                  emoji: '🟫',
                  description: 'The most basic vip',
                },
                {
                  label: "Vip Silver",
                  value: "Silver",
                  emoji: '⬜',
                  description:'An intermediate vip',
                },
                {
                  label: "Vip Golden",
                  value: "Golden",
                  emoji: '🟨',
                  description:'A better vip',
                },
                {
                  label: "VIP Diamond",
                  value: "Diamond",
                  emoji: '🟦',
                  description:'The best vip of all',
                },
              ]),
            );

            const m = await message.channel.send({embeds: [embed], components: [row]})
            const ifilter = i => i.user.id === message.author.id;
            const collector = m.createMessageComponentCollector({filter: ifilter, time: 60000})
            collector.on("collect", async i => {
              if (i.values[0] === "Bronze") {
                ped = 'notavailable'
                car = 1
                money = 1000
            }else if (i.values[0] === "Silver"){
                ped = 'notavailable'
                car = 2
                money = 2000
            } else if (i.values[0] === "Golden"){
                ped = 1
                car = 3
                money = 3000
                }
            else if (i.values[0] === "Diamond"){
                ped = 1
                car = 5
                money = 4000
                }
                const embed = new MessageEmbed()
                .setTitle('VIP Code Generated')
                .setDescription(`VIP  \`${i.values[0]}\` \`${codigo}\` generated by ${message.author}`)
                .setColor('GOLD')
                message.channel.send({embeds: [embed]})
                return exports['fly_vipsystem'].GenerateCode(codigo, i.values[0], car, ped, money);
            })
    }
    if (args[0] == config.prefix + 'givevip') {
      if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.reply(`${message.author} **You do not have permissions to use this command.**`); 
        if (args[1]) {
            const embed = new MessageEmbed()
            .setTitle('Select the type of vip')
            .setColor('GOLD')
            const row = new MessageActionRow()
            .addComponents(
              new MessageSelectMenu()
              .setCustomId('typevip')
              .setPlaceholder('Select it here')
              .addOptions([{
                  label: "VIP Bronze",
                  value: "Bronze",
                  emoji: '🟫',
                  description: 'The most basic vip',
                },
                {
                  label: "Vip Silver",
                  value: "Silver",
                  emoji: '⬜',
                  description:'An intermediate vip',
                },
                {
                  label: "Vip Golden",
                  value: "Golden",
                  emoji: '🟨',
                  description:'A better vip',
                },
                {
                  label: "VIP Diamond",
                  value: "Diamond",
                  emoji: '🟦',
                  description:'The best vip of all',
                },
              ]),
            );

            const m = await message.channel.send({embeds: [embed], components: [row]})
            const ifilter = i => i.user.id === message.author.id;
            const collector = m.createMessageComponentCollector({filter: ifilter, time: 60000})
            collector.on("collect", async i => {
              if (i.values[0] === "Bronze") {
                ped = 'notavailable'
                car = 1
                money = 1000
            }else if (i.values[0] === "Silver"){
                ped = 'notavailable'
                car = 2
                money = 2000
            } else if (i.values[0] === "Golden"){
                ped = 1
                car = 3
                money = 3000
                }
            else if (i.values[0] === "Diamond"){
                ped = 1
                car = 5
                money = 4000
                }
                return exports['fly_vipsystem'].GiveVip(args[1], i.values[0], car, ped, money);
            })

          }
        else {
      const embedfail = new MessageEmbed()
          .setTitle('You must put an ID or a rockstar license.')
          .setColor('RED')

          message.channel.send({embeds: [embedfail]})
      }
  }
  
  if (args[0] == config.prefix + 'removevip') {
    if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.reply(`${message.author} **You do not have permissions to use this command.**`); 
    if (args[1]) {
      const embed = new MessageEmbed()
      .setTitle('VIP Removed')
      .setDescription(`${message.author} has withdrawn vip access to ${args[1]}`)
      .setColor('RED')

      message.channel.send({embeds: [embed]})
      return exports['fly_vipsystem'].Removevip(args[1]);
  }
               else {
  const embedfail = new MessageEmbed()
      .setTitle('You must put an ID or a rockstar license.')
      .setColor('RED')

      message.channel.send({embeds: [embedfail]})
  }
}

if (args[0] == config.prefix + 'vips') {
  if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.reply(`${message.author} **You do not have permissions to use this command.**`); 
      return exports['fly_vipsystem'].SearchVip();
}

if (args[0] == config.prefix + 'setped') {
  if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.reply(`${message.author} **You do not have permissions to use this command.**`); 
  if (args[2]) {
    return exports['fly_vipsystem'].SetPed(args[1], args[2]);
}
  else {
const embedfail = new MessageEmbed()
    .setTitle('You must put an ID or a rockstar license. o no has nombrado el ped')
    .setColor('RED')
    message.channel.send({embeds: [embedfail]})
  }}

 }})



RegisterNetEvent('fly_vipsystem:SendEmbed')
on('fly_vipsystem:SendEmbed', embed => SendEmbed(embed));
 
 SendEmbed = (embed) => {
      const CreateEmbed = new MessageEmbed()
      .setTitle(embed.title)
      .setColor(embed.color) 
      .setDescription(embed.description)
      
      if (embed.fields) {
           for (x in embed.fields) CreateEmbed.addField(embed.fields[x].name, embed.fields[x].value, embed.fields[x].inline || false);
      }
    //   return CreateEmbed
      CurrentChannel.send({embeds: [CreateEmbed]})
    }

client.login(config.token).catch(e => client.logger.error(e.message));